//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PythonTools.Analysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PythonTools.Analysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BreakMultipleStatementsPerLineLong {
            get {
                return ResourceManager.GetString("BreakMultipleStatementsPerLineLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break multiple statements on a single line into multiple lines.
        /// </summary>
        internal static string BreakMultipleStatementsPerLineShort {
            get {
                return ResourceManager.GetString("BreakMultipleStatementsPerLineShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LinesBetweenLevelDeclarationsLong {
            get {
                return ResourceManager.GetString("LinesBetweenLevelDeclarationsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines between top level definitions.
        /// </summary>
        internal static string LinesBetweenLevelDeclarationsShort {
            get {
                return ResourceManager.GetString("LinesBetweenLevelDeclarationsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LinesBetweenMethodsInClassLong {
            get {
                return ResourceManager.GetString("LinesBetweenMethodsInClassLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines between methods in a class definition.
        /// </summary>
        internal static string LinesBetweenMethodsInClassShort {
            get {
                return ResourceManager.GetString("LinesBetweenMethodsInClassShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemoveExtraLinesBetweenMethodsLong {
            get {
                return ResourceManager.GetString("RemoveExtraLinesBetweenMethodsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extra lines between methods.
        /// </summary>
        internal static string RemoveExtraLinesBetweenMethodsShort {
            get {
                return ResourceManager.GetString("RemoveExtraLinesBetweenMethodsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemoveTrailingSemicolonsLong {
            get {
                return ResourceManager.GetString("RemoveTrailingSemicolonsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove trailing semicolons.
        /// </summary>
        internal static string RemoveTrailingSemicolonsShort {
            get {
                return ResourceManager.GetString("RemoveTrailingSemicolonsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReplaceMultipleImportsWithMultipleStatementsLong {
            get {
                return ResourceManager.GetString("ReplaceMultipleImportsWithMultipleStatementsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace multiple imports on a single line with multiple imports.
        /// </summary>
        internal static string ReplaceMultipleImportsWithMultipleStatementsShort {
            get {
                return ResourceManager.GetString("ReplaceMultipleImportsWithMultipleStatementsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceAroundAnnotationArrowLong {
            get {
                return ResourceManager.GetString("SpaceAroundAnnotationArrowLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces around the arrow annotation in a function definition..
        /// </summary>
        internal static string SpaceAroundAnnotationArrowShort {
            get {
                return ResourceManager.GetString("SpaceAroundAnnotationArrowShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceAroundDefaultValueEqualsLong {
            get {
                return ResourceManager.GetString("SpaceAroundDefaultValueEqualsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces around the equals for a default value in a parameter list.
        /// </summary>
        internal static string SpaceAroundDefaultValueEqualsShort {
            get {
                return ResourceManager.GetString("SpaceAroundDefaultValueEqualsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceBeforeCallParenLong {
            get {
                return ResourceManager.GetString("SpaceBeforeCallParenLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space before the parenthesis in a call expression.
        /// </summary>
        internal static string SpaceBeforeCallParenShort {
            get {
                return ResourceManager.GetString("SpaceBeforeCallParenShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled spaces are inserted before the parenthesis in a class declaration, if disabled removes the spaces, otherwise formatting is unchanged..
        /// </summary>
        internal static string SpaceBeforeClassDeclarationParenLong {
            get {
                return ResourceManager.GetString("SpaceBeforeClassDeclarationParenLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space before the parenthesis in a class declaration.
        /// </summary>
        internal static string SpaceBeforeClassDeclarationParenShort {
            get {
                return ResourceManager.GetString("SpaceBeforeClassDeclarationParenShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceBeforeFunctionDeclarationParenLong {
            get {
                return ResourceManager.GetString("SpaceBeforeFunctionDeclarationParenLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space before the opening parenthesis in a function definition.
        /// </summary>
        internal static string SpaceBeforeFunctionDeclarationParenShort {
            get {
                return ResourceManager.GetString("SpaceBeforeFunctionDeclarationParenShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceBeforeIndexBracketLong {
            get {
                return ResourceManager.GetString("SpaceBeforeIndexBracketLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space before bracket in index expression.
        /// </summary>
        internal static string SpaceBeforeIndexBracketShort {
            get {
                return ResourceManager.GetString("SpaceBeforeIndexBracketShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpacesAroundAssignmentOperatorLong {
            get {
                return ResourceManager.GetString("SpacesAroundAssignmentOperatorLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces around assignment operator.
        /// </summary>
        internal static string SpacesAroundAssignmentOperatorShort {
            get {
                return ResourceManager.GetString("SpacesAroundAssignmentOperatorShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpacesAroundBinaryOperatorsLong {
            get {
                return ResourceManager.GetString("SpacesAroundBinaryOperatorsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces around binary operators.
        /// </summary>
        internal static string SpacesAroundBinaryOperatorsShort {
            get {
                return ResourceManager.GetString("SpacesAroundBinaryOperatorsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpacesWithinEmptyListExpressionLong {
            get {
                return ResourceManager.GetString("SpacesWithinEmptyListExpressionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces within empty list expression.
        /// </summary>
        internal static string SpacesWithinEmptyListExpressionShort {
            get {
                return ResourceManager.GetString("SpacesWithinEmptyListExpressionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpacesWithinListExpressionLong {
            get {
                return ResourceManager.GetString("SpacesWithinListExpressionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces within list expression.
        /// </summary>
        internal static string SpacesWithinListExpressionShort {
            get {
                return ResourceManager.GetString("SpacesWithinListExpressionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpacesWithinParenthesisedTupleExpressionLong {
            get {
                return ResourceManager.GetString("SpacesWithinParenthesisedTupleExpressionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces within parenthesised tuple expression.
        /// </summary>
        internal static string SpacesWithinParenthesisedTupleExpressionShort {
            get {
                return ResourceManager.GetString("SpacesWithinParenthesisedTupleExpressionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpacesWithinParenthesisExpressionLong {
            get {
                return ResourceManager.GetString("SpacesWithinParenthesisExpressionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces within parenthesis expression.
        /// </summary>
        internal static string SpacesWithinParenthesisExpressionShort {
            get {
                return ResourceManager.GetString("SpacesWithinParenthesisExpressionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceWithinCallParensLong {
            get {
                return ResourceManager.GetString("SpaceWithinCallParensLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within the parenthesis in a call expression.
        /// </summary>
        internal static string SpaceWithinCallParensShort {
            get {
                return ResourceManager.GetString("SpaceWithinCallParensShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled spaces are inserted within the parenthesis in a class declaration, if disabled removes the spaces, otherwise formatting is unchanged..
        /// </summary>
        internal static string SpaceWithinClassDeclarationParensLong {
            get {
                return ResourceManager.GetString("SpaceWithinClassDeclarationParensLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within the parenthesis in a class definition.
        /// </summary>
        internal static string SpaceWithinClassDeclarationParensShort {
            get {
                return ResourceManager.GetString("SpaceWithinClassDeclarationParensShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled a space is inserted within the parenthesis in a class declaration when no bases are listed, if disabled removes the space, otherwise formatting is unchanged..
        /// </summary>
        internal static string SpaceWithinEmptyBaseClassListLong {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyBaseClassListLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within empty base class list for a class definition.
        /// </summary>
        internal static string SpaceWithinEmptyBaseClassListShort {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyBaseClassListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceWithinEmptyCallArgumentListLong {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyCallArgumentListLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces within the parenthesis in a call expression with no arguments.
        /// </summary>
        internal static string SpaceWithinEmptyCallArgumentListShort {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyCallArgumentListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceWithinEmptyParameterListLong {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyParameterListLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within empty parameter list for a function definition.
        /// </summary>
        internal static string SpaceWithinEmptyParameterListShort {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyParameterListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceWithinEmptyTupleExpressionLong {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyTupleExpressionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within empty parenthesis expression.
        /// </summary>
        internal static string SpaceWithinEmptyTupleExpressionShort {
            get {
                return ResourceManager.GetString("SpaceWithinEmptyTupleExpressionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceWithinFunctionDeclarationParensLong {
            get {
                return ResourceManager.GetString("SpaceWithinFunctionDeclarationParensLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within the parenthesis in a function definition.
        /// </summary>
        internal static string SpaceWithinFunctionDeclarationParensShort {
            get {
                return ResourceManager.GetString("SpaceWithinFunctionDeclarationParensShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpaceWithinIndexBracketsLong {
            get {
                return ResourceManager.GetString("SpaceWithinIndexBracketsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space within brackets in index expression.
        /// </summary>
        internal static string SpaceWithinIndexBracketsShort {
            get {
                return ResourceManager.GetString("SpaceWithinIndexBracketsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WrapCommentsLong {
            get {
                return ResourceManager.GetString("WrapCommentsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap comment lines.
        /// </summary>
        internal static string WrapCommentsShort {
            get {
                return ResourceManager.GetString("WrapCommentsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WrapDocStringsLong {
            get {
                return ResourceManager.GetString("WrapDocStringsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap doc strings.
        /// </summary>
        internal static string WrapDocStringsShort {
            get {
                return ResourceManager.GetString("WrapDocStringsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WrappingWidthLong {
            get {
                return ResourceManager.GetString("WrappingWidthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapping width.
        /// </summary>
        internal static string WrappingWidthShort {
            get {
                return ResourceManager.GetString("WrappingWidthShort", resourceCulture);
            }
        }
    }
}
