//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PythonTools.ProjectWizards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PythonTools.ProjectWizards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are a free download for your version of Visual Studio.
        ///
        ///After installation, you will need to restart Visual Studio..
        /// </summary>
        internal static string AzureToolsInstallInstructions {
            get {
                return ResourceManager.GetString("AzureToolsInstallInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project type requires the Azure Tools for Visual Studio..
        /// </summary>
        internal static string AzureToolsRequired {
            get {
                return ResourceManager.GetString("AzureToolsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your default environment.
        /// </summary>
        internal static string DefaultInterpreterDescription {
            get {
                return ResourceManager.GetString("DefaultInterpreterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install now.
        /// </summary>
        internal static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start wizard: no automation object available..
        /// </summary>
        internal static string ErrorNoDte {
            get {
                return ResourceManager.GetString("ErrorNoDte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your packages may not have been installed..
        /// </summary>
        internal static string InstallRequirementsFailed {
            get {
                return ResourceManager.GetString("InstallRequirementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;https://pytools.codeplex.com/workitem/2446&quot;&gt;What do you think about this dialog?&lt;/a&gt;.
        /// </summary>
        internal static string InstallRequirementsFooter {
            get {
                return ResourceManager.GetString("InstallRequirementsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project requires external packages.
        /// </summary>
        internal static string InstallRequirementsHeading {
            get {
                return ResourceManager.GetString("InstallRequirementsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide required &amp;packages.
        /// </summary>
        internal static string InstallRequirementsHidePackages {
            get {
                return ResourceManager.GetString("InstallRequirementsHidePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install into {0}.
        /// </summary>
        internal static string InstallRequirementsIntoGlobalEnv {
            get {
                return ResourceManager.GetString("InstallRequirementsIntoGlobalEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages will be shared by all projects.
        /// </summary>
        internal static string InstallRequirementsIntoGlobalEnvTip {
            get {
                return ResourceManager.GetString("InstallRequirementsIntoGlobalEnvTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install into a &amp;virtual environment....
        /// </summary>
        internal static string InstallRequirementsIntoVirtualEnv {
            get {
                return ResourceManager.GetString("InstallRequirementsIntoVirtualEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages will only be available for this project (recommended).
        /// </summary>
        internal static string InstallRequirementsIntoVirtualEnvTip {
            get {
                return ResourceManager.GetString("InstallRequirementsIntoVirtualEnvTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can download and install these packages for you automatically, but we need to know whether you want to install them for just this project or for all your projects..
        /// </summary>
        internal static string InstallRequirementsMessage {
            get {
                return ResourceManager.GetString("InstallRequirementsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will install them &amp;myself.
        /// </summary>
        internal static string InstallRequirementsNowhere {
            get {
                return ResourceManager.GetString("InstallRequirementsNowhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show required &amp;packages.
        /// </summary>
        internal static string InstallRequirementsShowPackages {
            get {
                return ResourceManager.GetString("InstallRequirementsShowPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Tools for Visual Studio.
        /// </summary>
        internal static string PythonToolsForVisualStudio {
            get {
                return ResourceManager.GetString("PythonToolsForVisualStudio", resourceCulture);
            }
        }
    }
}
