//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PythonTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string CompletionFilterClass {
            get {
                return ResourceManager.GetString("CompletionFilterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string CompletionFilterColor {
            get {
                return ResourceManager.GetString("CompletionFilterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        internal static string CompletionFilterConstant {
            get {
                return ResourceManager.GetString("CompletionFilterConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructors.
        /// </summary>
        internal static string CompletionFilterConstructor {
            get {
                return ResourceManager.GetString("CompletionFilterConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        internal static string CompletionFilterEnum {
            get {
                return ResourceManager.GetString("CompletionFilterEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum members.
        /// </summary>
        internal static string CompletionFilterEnumMember {
            get {
                return ResourceManager.GetString("CompletionFilterEnumMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string CompletionFilterEvent {
            get {
                return ResourceManager.GetString("CompletionFilterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string CompletionFilterField {
            get {
                return ResourceManager.GetString("CompletionFilterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string CompletionFilterFile {
            get {
                return ResourceManager.GetString("CompletionFilterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string CompletionFilterFolder {
            get {
                return ResourceManager.GetString("CompletionFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string CompletionFilterFunction {
            get {
                return ResourceManager.GetString("CompletionFilterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        internal static string CompletionFilterInterface {
            get {
                return ResourceManager.GetString("CompletionFilterInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string CompletionFilterKeyword {
            get {
                return ResourceManager.GetString("CompletionFilterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        internal static string CompletionFilterMethod {
            get {
                return ResourceManager.GetString("CompletionFilterMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string CompletionFilterModule {
            get {
                return ResourceManager.GetString("CompletionFilterModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        internal static string CompletionFilterOperator {
            get {
                return ResourceManager.GetString("CompletionFilterOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string CompletionFilterProperty {
            get {
                return ResourceManager.GetString("CompletionFilterProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string CompletionFilterReference {
            get {
                return ResourceManager.GetString("CompletionFilterReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        internal static string CompletionFilterSnippet {
            get {
                return ResourceManager.GetString("CompletionFilterSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs.
        /// </summary>
        internal static string CompletionFilterStruct {
            get {
                return ResourceManager.GetString("CompletionFilterStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string CompletionFilterText {
            get {
                return ResourceManager.GetString("CompletionFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameters.
        /// </summary>
        internal static string CompletionFilterTypeParameter {
            get {
                return ResourceManager.GetString("CompletionFilterTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string CompletionFilterUnit {
            get {
                return ResourceManager.GetString("CompletionFilterUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string CompletionFilterValue {
            get {
                return ResourceManager.GetString("CompletionFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string CompletionFilterVariable {
            get {
                return ResourceManager.GetString("CompletionFilterVariable", resourceCulture);
            }
        }
    }
}
