//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PythonTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interpreter that was used to create this virtual environment..
        /// </summary>
        internal static string BaseInterpreterDescription {
            get {
                return ResourceManager.GetString("BaseInterpreterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Interpreter.
        /// </summary>
        internal static string BaseInterpreterDisplayName {
            get {
                return ResourceManager.GetString("BaseInterpreterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following packages will be installed from PyPI in order to run this command:
        ///
        ///{0}
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string CustomCommandPrerequisitesInstallPrompt {
            get {
                return ResourceManager.GetString("CustomCommandPrerequisitesInstallPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Interactive Window.
        /// </summary>
        internal static string CustomCommandReplTitle {
            get {
                return ResourceManager.GetString("CustomCommandReplTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start &amp;debug server.
        /// </summary>
        internal static string DebugWebServerLabel {
            get {
                return ResourceManager.GetString("DebugWebServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches and debugs Python programs. This is the default..
        /// </summary>
        internal static string DefaultLauncherDescription {
            get {
                return ResourceManager.GetString("DefaultLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Python launcher.
        /// </summary>
        internal static string DefaultLauncherName {
            get {
                return ResourceManager.GetString("DefaultLauncherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will be removed from the project and the directory
        ///&apos;{1}&apos;
        ///and all its contents will be deleted from disk..
        /// </summary>
        internal static string EnvironmentDeleteConfirmation {
            get {
                return ResourceManager.GetString("EnvironmentDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We weren&apos;t able to delete all the files from {0}.
        ///
        ///Some files may need to be removed manually..
        /// </summary>
        internal static string EnvironmentDeleteError {
            get {
                return ResourceManager.GetString("EnvironmentDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the environment..
        /// </summary>
        internal static string EnvironmentIdDescription {
            get {
                return ResourceManager.GetString("EnvironmentIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string EnvironmentIdDisplayName {
            get {
                return ResourceManager.GetString("EnvironmentIdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will be removed from the project.
        ///No files will be deleted from disk..
        /// </summary>
        internal static string EnvironmentRemoveConfirmation {
            get {
                return ResourceManager.GetString("EnvironmentRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Environments.
        /// </summary>
        internal static string Environments {
            get {
                return ResourceManager.GetString("Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Python language version supported by the environment..
        /// </summary>
        internal static string EnvironmentVersionDescription {
            get {
                return ResourceManager.GetString("EnvironmentVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string EnvironmentVersionDisplayName {
            get {
                return ResourceManager.GetString("EnvironmentVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get command {0} from project.
        /// </summary>
        internal static string ErrorBuildingCustomCommand {
            get {
                return ResourceManager.GetString("ErrorBuildingCustomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command is already running..
        /// </summary>
        internal static string ErrorCommandAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorCommandAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error {0} occurred while creating your project.
        ///
        ///If Visual Studio is running with the /Log option, the full exception has been written to the activity log..
        /// </summary>
        internal static string ErrorImportWizardException {
            get {
                return ResourceManager.GetString("ErrorImportWizardException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some file paths could not be accessed.
        ///
        ///Try moving your source code to a location where you can read and write files..
        /// </summary>
        internal static string ErrorImportWizardUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ErrorImportWizardUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while running {0}.
        ///
        ///{1}.
        /// </summary>
        internal static string ErrorRunningCustomCommand {
            get {
                return ResourceManager.GetString("ErrorRunningCustomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExecutingStartupScript {
            get {
                return ResourceManager.GetString("ExecutingStartupScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get resource {1}.{2} from {0}.
        ///
        ///{3}.
        /// </summary>
        internal static string FailedToReadResource {
            get {
                return ResourceManager.GetString("FailedToReadResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Comment Paragraph fills the text in a contiguous block of comment lines or multiline strings.
        ///
        ///It must be invoked on a comment line or within a triple quoted line..
        /// </summary>
        internal static string FillCommentSelectionError {
            get {
                return ResourceManager.GetString("FillCommentSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified project file already exists. Overwrite?.
        /// </summary>
        internal static string ImportWizardProjectExists {
            get {
                return ResourceManager.GetString("ImportWizardProjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InitializingFromProject {
            get {
                return ResourceManager.GetString("InitializingFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install your Python package, we will install setuptools and the pip package manager.
        ///
        ///Continue?.
        /// </summary>
        internal static string InstallEasyInstall {
            get {
                return ResourceManager.GetString("InstallEasyInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install your Python package, we will install the pip package manager.
        ///
        ///Continue?.
        /// </summary>
        internal static string InstallPip {
            get {
                return ResourceManager.GetString("InstallPip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create your virtual environment, we will install the virtualenv package.
        ///
        ///Continue?.
        /// </summary>
        internal static string InstallVirtualEnv {
            get {
                return ResourceManager.GetString("InstallVirtualEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a virtual environment, we will install the pip package manager and the virtualenv package.
        ///
        ///Continue?.
        /// </summary>
        internal static string InstallVirtualEnvAndPip {
            get {
                return ResourceManager.GetString("InstallVirtualEnvAndPip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MissingStartupScript {
            get {
                return ResourceManager.GetString("MissingStartupScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Python environments are configured. Please install or configure an environment and try again..
        /// </summary>
        internal static string NoInterpretersAvailable {
            get {
                return ResourceManager.GetString("NoInterpretersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no surveys or news available at this time.  Please check again later..
        /// </summary>
        internal static string NoSurveyNewsAvailable {
            get {
                return ResourceManager.GetString("NoSurveyNewsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string PackageFullName {
            get {
                return ResourceManager.GetString("PackageFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name of the package, including the version if known..
        /// </summary>
        internal static string PackageFullNameDescription {
            get {
                return ResourceManager.GetString("PackageFullNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; failed to install..
        /// </summary>
        internal static string PackageInstallFailed {
            get {
                return ResourceManager.GetString("PackageInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; failed to install. Exit code: {1}.
        /// </summary>
        internal static string PackageInstallFailedExitCode {
            get {
                return ResourceManager.GetString("PackageInstallFailedExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos;.
        /// </summary>
        internal static string PackageInstalling {
            get {
                return ResourceManager.GetString("PackageInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos;. See output window for more information..
        /// </summary>
        internal static string PackageInstallingSeeOutputWindow {
            get {
                return ResourceManager.GetString("PackageInstallingSeeOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was installed successfully..
        /// </summary>
        internal static string PackageInstallSucceeded {
            get {
                return ResourceManager.GetString("PackageInstallSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; failed to uninstall..
        /// </summary>
        internal static string PackageUninstallFailed {
            get {
                return ResourceManager.GetString("PackageUninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; failed to uninstall. Exit code: {1}.
        /// </summary>
        internal static string PackageUninstallFailedExitCode {
            get {
                return ResourceManager.GetString("PackageUninstallFailedExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnstalling &apos;{0}&apos;.
        /// </summary>
        internal static string PackageUninstalling {
            get {
                return ResourceManager.GetString("PackageUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnstalling &apos;{0}&apos;. See output window for more information..
        /// </summary>
        internal static string PackageUninstallingSeeOutputWindow {
            get {
                return ResourceManager.GetString("PackageUninstallingSeeOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was uninstalled successfully..
        /// </summary>
        internal static string PackageUninstallSucceeded {
            get {
                return ResourceManager.GetString("PackageUninstallSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;pip&apos; failed to install..
        /// </summary>
        internal static string PipInstallFailed {
            get {
                return ResourceManager.GetString("PipInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;pip&apos; failed to install. Exit code: {0}.
        /// </summary>
        internal static string PipInstallFailedExitCode {
            get {
                return ResourceManager.GetString("PipInstallFailedExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;pip&apos; package manager..
        /// </summary>
        internal static string PipInstalling {
            get {
                return ResourceManager.GetString("PipInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;pip&apos; was installed successfully..
        /// </summary>
        internal static string PipInstallSucceeded {
            get {
                return ResourceManager.GetString("PipInstallSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Python.
        /// </summary>
        internal static string PythonMenuLabel {
            get {
                return ResourceManager.GetString("PythonMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Tools for Visual Studio.
        /// </summary>
        internal static string PythonToolsForVisualStudio {
            get {
                return ResourceManager.GetString("PythonToolsForVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches web sites using the Python debugger. This enables launching and starting a web browser automatically, using the commands specified in the project file..
        /// </summary>
        internal static string PythonWebLauncherDescription {
            get {
                return ResourceManager.GetString("PythonWebLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web launcher.
        /// </summary>
        internal static string PythonWebLauncherName {
            get {
                return ResourceManager.GetString("PythonWebLauncherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string ReferencesNodeName {
            get {
                return ResourceManager.GetString("ReferencesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be started because the path to the interpreter has not been configured.
        ///Please update the environment in Tools-&gt;Options-&gt;Python Tools-&gt;Environment Options
        ///.
        /// </summary>
        internal static string ReplEvaluatorInterpreterNotConfigured {
            get {
                return ResourceManager.GetString("ReplEvaluatorInterpreterNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interactive window could not be started because the associated Python environment could not be found.
        ///If this version of Python has recently been uninstalled, you can close this window.
        ///.
        /// </summary>
        internal static string ReplEvaluatorInterpreterNotFound {
            get {
                return ResourceManager.GetString("ReplEvaluatorInterpreterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python interactive window. Type $help for a list of commands..
        /// </summary>
        internal static string ReplInitializationMessage {
            get {
                return ResourceManager.GetString("ReplInitializationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start server.
        /// </summary>
        internal static string RunWebServerLabel {
            get {
                return ResourceManager.GetString("RunWebServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Paths Properties.
        /// </summary>
        internal static string SearchPathContainerProperties {
            get {
                return ResourceManager.GetString("SearchPathContainerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Path Properties.
        /// </summary>
        internal static string SearchPathProperties {
            get {
                return ResourceManager.GetString("SearchPathProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will be removed from the project&apos;s search path..
        /// </summary>
        internal static string SearchPathRemoveConfirmation {
            get {
                return ResourceManager.GetString("SearchPathRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Paths.
        /// </summary>
        internal static string SearchPaths {
            get {
                return ResourceManager.GetString("SearchPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of directories to search for modules and files..
        /// </summary>
        internal static string SearchPathsDescription {
            get {
                return ResourceManager.GetString("SearchPathsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SettingWorkDir {
            get {
                return ResourceManager.GetString("SettingWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred and your project was not created..
        /// </summary>
        internal static string StatusImportWizardError {
            get {
                return ResourceManager.GetString("StatusImportWizardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing project....
        /// </summary>
        internal static string StatusImportWizardStarting {
            get {
                return ResourceManager.GetString("StatusImportWizardStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Command Line.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will be uninstalled from {1} ({2})..
        /// </summary>
        internal static string UninstallPackage {
            get {
                return ResourceManager.GetString("UninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve &quot;{0}&quot;. IntelliSense may be missing for this module..
        /// </summary>
        internal static string UnresolvedModuleTooltip {
            get {
                return ResourceManager.GetString("UnresolvedModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve &quot;{0}&quot;.
        ///The completion DB for the active environment needs to be refreshed,
        ///and IntelliSense may be missing until that has completed.
        ///See the Python Environments window for details..
        /// </summary>
        internal static string UnresolvedModuleTooltipRefreshing {
            get {
                return ResourceManager.GetString("UnresolvedModuleTooltipRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UpdatingSearchPath {
            get {
                return ResourceManager.GetString("UpdatingSearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tools version has been changed to 4.0. This will not affect compatibility with other versions of Visual Studio..
        /// </summary>
        internal static string UpgradedToolsVersion {
            get {
                return ResourceManager.GetString("UpgradedToolsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install/upgrade {PythonWebFrameworkPackageDisplayName}.
        /// </summary>
        internal static string UpgradeWebFrameworkLabel {
            get {
                return ResourceManager.GetString("UpgradeWebFrameworkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual environment is being created at &apos;{0}&apos;.
        /// </summary>
        internal static string VirtualEnvCreating {
            get {
                return ResourceManager.GetString("VirtualEnvCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual environment was not created at &apos;{0}&apos;.
        /// </summary>
        internal static string VirtualEnvCreationFailed {
            get {
                return ResourceManager.GetString("VirtualEnvCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual environment was not created at &apos;{0}&apos;. Exit code: {1}.
        /// </summary>
        internal static string VirtualEnvCreationFailedExitCode {
            get {
                return ResourceManager.GetString("VirtualEnvCreationFailedExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual environment was successfully created at &apos;{0}&apos;.
        /// </summary>
        internal static string VirtualEnvCreationSucceeded {
            get {
                return ResourceManager.GetString("VirtualEnvCreationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the IntelliSense database is currently not up to date and completions may be missing..
        /// </summary>
        internal static string WarningAnalysisNotCurrent {
            get {
                return ResourceManager.GetString("WarningAnalysisNotCurrent", resourceCulture);
            }
        }
    }
}
