//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TC.TestHostAdapters
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TC.TestHostAdapters.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find specified process..
        /// </summary>
        internal static string CannotFindProcess {
            get {
                return ResourceManager.GetString("CannotFindProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find installation of Visual Studio in &apos;{0}&apos; registry hive..
        /// </summary>
        internal static string CannotFindVSInstallation {
            get {
                return ResourceManager.GetString("CannotFindVSInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: TC VS IDE Host Adapter: error shutting down VS IDE: {0}.
        /// </summary>
        internal static string ErrorShuttingDownVS {
            get {
                return ResourceManager.GetString("ErrorShuttingDownVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: TC VS IDE Host Adapter failed to call ITestAdapter.Cleanup: {0}.
        /// </summary>
        internal static string FailedToCallTACleanup {
            get {
                return ResourceManager.GetString("FailedToCallTACleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: TC VS IDE Host Adapter failed to detach debugger: {0}.
        /// </summary>
        internal static string FailedToDetachDebugger {
            get {
                return ResourceManager.GetString("FailedToDetachDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: TC VS IDE Host Adapter: failed to connect to the debugger, debugging tests running in Visual Studio process will be disabled: {0}.
        /// </summary>
        internal static string FailedToGetDebugger {
            get {
                return ResourceManager.GetString("FailedToGetDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the DTE object from Visual Studio process. Please make sure that the Add-in is registered in Tools-&gt;Add-in Manager to load in when Visual Studio starts..
        /// </summary>
        internal static string FailedToGetDte {
            get {
                return ResourceManager.GetString("FailedToGetDte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC VS IDE Host Adapter: Failed to initialize the host side: {0}.
        /// </summary>
        internal static string FailedToInitHostSide {
            get {
                return ResourceManager.GetString("FailedToInitHostSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Visual Studio process..
        /// </summary>
        internal static string FailedToStartVSProcess {
            get {
                return ResourceManager.GetString("FailedToStartVSProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Adapter that allows to run tests inside Visual Studio.
        /// </summary>
        internal static string HostAdapterDescription {
            get {
                return ResourceManager.GetString("HostAdapterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio.
        /// </summary>
        internal static string MicrosoftVisualStudio {
            get {
                return ResourceManager.GetString("MicrosoftVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC VS IDE Test Host Configuration Data.
        /// </summary>
        internal static string RunConfigDataDescription {
            get {
                return ResourceManager.GetString("RunConfigDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out getting Vs Ide Test Host Add-in from Visual Studio. Please make sure that the Add-in is installed and started when VS starts (use Tools-&gt;Add-in Manager)..
        /// </summary>
        internal static string TimedOutGettingAddin {
            get {
                return ResourceManager.GetString("TimedOutGettingAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out getting VS.DTE from COM Running Object Table..
        /// </summary>
        internal static string TimedOutGettingDteFromRot {
            get {
                return ResourceManager.GetString("TimedOutGettingDteFromRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: timed out calling Dte.Quit: all the calls were rejected. Visual Studio process will be killed..
        /// </summary>
        internal static string TimedOutWaitingDteQuit {
            get {
                return ResourceManager.GetString("TimedOutWaitingDteQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio process exited unexpectedly..
        /// </summary>
        internal static string VSExitedUnexpectedly {
            get {
                return ResourceManager.GetString("VSExitedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Registry Hive.
        /// </summary>
        internal static string VSRegistryHive {
            get {
                return ResourceManager.GetString("VSRegistryHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value of Visual Studio version in the Test Run Configuration file: &apos;{0}&apos;. Latest version &apos;{1}&apos; will be used..
        /// </summary>
        internal static string WrongVSVersionPassedToRunConfigControl {
            get {
                return ResourceManager.GetString("WrongVSVersionPassedToRunConfigControl", resourceCulture);
            }
        }
    }
}
