//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PythonTools.EnvironmentsList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PythonTools.EnvironmentsList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ConfigurationExtensionDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationExtensionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings may be configured for this environment. Check the tooltips for each field for more information and examples..
        /// </summary>
        internal static string ConfigurationExtensionHelpContent {
            get {
                return ResourceManager.GetString("ConfigurationExtensionHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntelliSense.
        /// </summary>
        internal static string DBExtensionDisplayName {
            get {
                return ResourceManager.GetString("DBExtensionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list shows the modules as detected by IntelliSense. If you do not see your library here, it may not be installed correctly..
        /// </summary>
        internal static string DBExtensionHelpContent {
            get {
                return ResourceManager.GetString("DBExtensionHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string EnvironmentPathsExtensionDisplayName {
            get {
                return ResourceManager.GetString("EnvironmentPathsExtensionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a quick overview of the environment. Use the links to open the paths, or right-click to copy them to the clipboard..
        /// </summary>
        internal static string EnvironmentPathsExtensionHelpContent {
            get {
                return ResourceManager.GetString("EnvironmentPathsExtensionHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        internal static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to install &apos;{0}&apos; -----
        ///.
        /// </summary>
        internal static string InstallingPackageFailed {
            get {
                return ResourceManager.GetString("InstallingPackageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Installing &apos;{0}&apos; -----.
        /// </summary>
        internal static string InstallingPackageStarted {
            get {
                return ResourceManager.GetString("InstallingPackageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully installed &apos;{0}&apos; -----
        ///.
        /// </summary>
        internal static string InstallingPackageSuccess {
            get {
                return ResourceManager.GetString("InstallingPackageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to install pip -----
        ///.
        /// </summary>
        internal static string InstallingPipFailed {
            get {
                return ResourceManager.GetString("InstallingPipFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Installing pip -----.
        /// </summary>
        internal static string InstallingPipStarted {
            get {
                return ResourceManager.GetString("InstallingPipStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully installed pip -----
        ///.
        /// </summary>
        internal static string InstallingPipSuccess {
            get {
                return ResourceManager.GetString("InstallingPipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating packages failed.
        /// </summary>
        internal static string ListFailed {
            get {
                return ResourceManager.GetString("ListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot be started because the environment is not configured..
        /// </summary>
        internal static string MisconfiguredEnvironment {
            get {
                return ResourceManager.GetString("MisconfiguredEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyPI.
        /// </summary>
        internal static string PipDefaultIndexName {
            get {
                return ResourceManager.GetString("PipDefaultIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pip.
        /// </summary>
        internal static string PipExtensionDisplayName {
            get {
                return ResourceManager.GetString("PipExtensionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These packages can be managed using pip. Type in the search box to install new packages, or use the buttons on the right to manage those that are already installed..
        /// </summary>
        internal static string PipExtensionHelpContent {
            get {
                return ResourceManager.GetString("PipExtensionHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Tools for Visual Studio.
        /// </summary>
        internal static string PythonToolsForVisualStudio {
            get {
                return ResourceManager.GetString("PythonToolsForVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation failed.
        /// </summary>
        internal static string UninstallationFailed {
            get {
                return ResourceManager.GetString("UninstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Error while uninstalling &apos;{0}&apos; -----
        ///&apos;{0}&apos; may not have been uninstalled completely.
        ///.
        /// </summary>
        internal static string UninstallingPackageFailed {
            get {
                return ResourceManager.GetString("UninstallingPackageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Uninstalling &apos;{0}&apos; -----.
        /// </summary>
        internal static string UninstallingPackageStarted {
            get {
                return ResourceManager.GetString("UninstallingPackageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully uninstalled &apos;{0}&apos; -----
        ///.
        /// </summary>
        internal static string UninstallingPackageSuccess {
            get {
                return ResourceManager.GetString("UninstallingPackageSuccess", resourceCulture);
            }
        }
    }
}
