// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.CookiecutterTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCookiecutterPkgString = "8261e28a-54ec-44d2-aded-8f9366b9196b";
        public const string guidCookiecutterCmdSetString = "6c1555d3-b9b7-4d39-b657-1a35a0f3c461";
        public const string guidPythonToolsCmdSetString = "bdfa79d2-2cd2-474a-a82a-ce8694116825";
        public const string guidCookiecutterImagesString = "50edf200-5c99-4968-abc0-cf1a2c490f00";
        public static Guid guidCookiecutterPkg = new Guid(guidCookiecutterPkgString);
        public static Guid guidCookiecutterCmdSet = new Guid(guidCookiecutterCmdSetString);
        public static Guid guidPythonToolsCmdSet = new Guid(guidPythonToolsCmdSetString);
        public static Guid guidCookiecutterImages = new Guid(guidCookiecutterImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidCookiecutterExplorer = 0x1001;
        public const int cmdidHome = 0x1002;
        public const int cmdidRun = 0x1003;
        public const int cmdidLinkGitHubHome = 0x1004;
        public const int cmdidLinkGitHubIssues = 0x1005;
        public const int cmdidLinkGitHubWiki = 0x1006;
        public const int cmdidCreateFromCookiecutter = 0x1007;
        public const int cmdidAddFromCookiecutter = 0x1008;
        public const int cmdidUpdateTemplate = 0x1009;
        public const int cmdidCheckForUpdates = 0x100A;
        public const int cmdidNewProjectFromTemplate = 0x100B;
        public const int cmdidViewExternalWebBrowser = 0x1100;
        public const int ContextMenu = 0x0065;
        public const int WindowToolBarId = 0x2000;
        public const int CookiecutterMenu = 0x2001;
        public const int ToolbarNavGroup = 0x3000;
        public const int ToolbarLinksGroup = 0x3001;
        public const int ContextNavGroup = 0x3002;
        public const int ContextLinksGroup = 0x3003;
        public const int WindowCommandsGroup = 0x1014;
        public const int Cancel = 0x0001;
        public const int Cookiecutter = 0x0002;
        public const int CookiecutterTemplate = 0x0003;
        public const int CookiecutterTemplateOK = 0x0004;
        public const int CookiecutterTemplateUpdate = 0x0005;
        public const int CookiecutterTemplateWarning = 0x0006;
        public const int Download = 0x0007;
        public const int NewCookiecutter = 0x0008;
    }
}
