// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.CookiecutterTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCookiecutterPkgString = "8261e28a-54ec-44d2-aded-8f9366b9196b";
        public const string guidCookiecutterCmdSetString = "6c1555d3-b9b7-4d39-b657-1a35a0f3c461";
        public static Guid guidCookiecutterPkg = new Guid(guidCookiecutterPkgString);
        public static Guid guidCookiecutterCmdSet = new Guid(guidCookiecutterCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidCookiecutter = 0x1001;
        public const int cmdidHome = 0x1002;
        public const int cmdidRun = 0x1003;
        public const int cmdidLinkGitHubHome = 0x1004;
        public const int cmdidLinkGitHubIssues = 0x1005;
        public const int cmdidLinkGitHubWiki = 0x1006;
        public const int ContextMenu = 0x0065;
        public const int WindowToolBarId = 0x2000;
        public const int ToolbarNavGroup = 0x3000;
        public const int ToolbarLinksGroup = 0x3001;
        public const int ContextNavGroup = 0x3002;
        public const int ContextLinksGroup = 0x3003;
    }
}
