//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CookiecutterTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CookiecutterTools.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files were successfully created, but there was an issue adding the files to your project.\n{0}.
        /// </summary>
        public static string AddToProjectError {
            get {
                return ResourceManager.GetString("AddToProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Check for template updates canceled -----.
        /// </summary>
        public static string CheckingForAllUpdatesCanceled {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to check for template updates -----.
        /// </summary>
        public static string CheckingForAllUpdatesFailed {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Checking for template updates -----.
        /// </summary>
        public static string CheckingForAllUpdatesStarted {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully checked for template updates -----.
        /// </summary>
        public static string CheckingForAllUpdatesSuccess {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for an update..
        /// </summary>
        public static string CheckingTemplateUpdateError {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        public static string CheckingTemplateUpdateFound {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine if an update is available..
        /// </summary>
        public static string CheckingTemplateUpdateInconclusive {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is already up-to-date..
        /// </summary>
        public static string CheckingTemplateUpdateNotFound {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Checking for update to template &apos;{0}&apos; from &apos;{1}&apos; -----.
        /// </summary>
        public static string CheckingTemplateUpdateStarted {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A different template with the name &apos;{0}&apos; already exists in &apos;{1}&apos;.
        ///
        ///Please delete the installed template and try again..
        /// </summary>
        public static string CloneCollisionMessage {
            get {
                return ResourceManager.GetString("CloneCollisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to clone template &apos;{0}&apos; -----.
        /// </summary>
        public static string CloningTemplateFailed {
            get {
                return ResourceManager.GetString("CloningTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Cloning template &apos;{0}&apos; -----.
        /// </summary>
        public static string CloningTemplateStarted {
            get {
                return ResourceManager.GetString("CloningTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully cloned template &apos;{0}&apos; to &apos;{1}&apos; -----.
        /// </summary>
        public static string CloningTemplateSuccess {
            get {
                return ResourceManager.GetString("CloningTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string appears to be in incorrect format. Would you like to re-create it?.
        /// </summary>
        public static string ConnectionStringFormatIncorrect {
            get {
                return ResourceManager.GetString("ConnectionStringFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; from _visual_studio section in context file should be an absolute http or https url..
        /// </summary>
        public static string CookiecutterClient_Invalidurl {
            get {
                return ResourceManager.GetString("CookiecutterClient_Invalidurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property is required on &apos;{1}&apos;..
        /// </summary>
        public static string CookiecutterClient_MissingProperty {
            get {
                return ResourceManager.GetString("CookiecutterClient_MissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter generated files must have a templated folder..
        /// </summary>
        public static string CookiecutterClient_MoveToDesiredFolderTemplatedFolderNotFound {
            get {
                return ResourceManager.GetString("CookiecutterClient_MoveToDesiredFolderTemplatedFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is referenced from _visual_studio section in context file but was not found..
        /// </summary>
        public static string CookiecutterClient_ReferenceNotFound {
            get {
                return ResourceManager.GetString("CookiecutterClient_ReferenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported json element type in context file for property &apos;{0}&apos;..
        /// </summary>
        public static string CookiecutterClient_UnsupportedJsonElementTypeForPorperty {
            get {
                return ResourceManager.GetString("CookiecutterClient_UnsupportedJsonElementTypeForPorperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; from _visual_studio section in context file should be of type &apos;{1}&apos;, instead of &apos;{2}&apos;..
        /// </summary>
        public static string CookiecutterClient_WrongJsonType {
            get {
                return ResourceManager.GetString("CookiecutterClient_WrongJsonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the template from this folder?
        ///
        ///{0}.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to delete template &apos;{0}&apos; -----.
        /// </summary>
        public static string DeletingTemplateFailed {
            get {
                return ResourceManager.GetString("DeletingTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Deleting template &apos;{0}&apos; -----.
        /// </summary>
        public static string DeletingTemplateStarted {
            get {
                return ResourceManager.GetString("DeletingTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully deleted template &apos;{0}&apos; -----.
        /// </summary>
        public static string DeletingTemplateSuccess {
            get {
                return ResourceManager.GetString("DeletingTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve results from feed.
        /// </summary>
        public static string FeedLoadError {
            get {
                return ResourceManager.GetString("FeedLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralPaneName {
            get {
                return ResourceManager.GetString("GeneralPaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve results from GitHub.
        /// </summary>
        public static string GitHubSearchError {
            get {
                return ResourceManager.GetString("GitHubSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.exe is not found. Please install Git, add it to PATH and try again..
        /// </summary>
        public static string GitNotFoundError {
            get {
                return ResourceManager.GetString("GitNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter makes it easy to generate code from a template..
        /// </summary>
        public static string InfoBarMessage {
            get {
                return ResourceManager.GetString("InfoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more..
        /// </summary>
        public static string InfoBarMessageLink {
            get {
                return ResourceManager.GetString("InfoBarMessageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Git.
        /// </summary>
        public static string InstallGitInfoBarLink {
            get {
                return ResourceManager.GetString("InstallGitInfoBarLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual environment at &apos;{0}&apos;.
        /// </summary>
        public static string InstallingCookiecutterCreateEnv {
            get {
                return ResourceManager.GetString("InstallingCookiecutterCreateEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create virtual environment at &apos;{0}&apos;.
        /// </summary>
        public static string InstallingCookiecutterCreateEnvFailed {
            get {
                return ResourceManager.GetString("InstallingCookiecutterCreateEnvFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual environment without pip at &apos;{0}&apos;.
        /// </summary>
        public static string InstallingCookiecutterCreateEnvWithoutPip {
            get {
                return ResourceManager.GetString("InstallingCookiecutterCreateEnvWithoutPip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting previous environment at &apos;{0}&apos;.
        /// </summary>
        public static string InstallingCookiecutterDeleteEnv {
            get {
                return ResourceManager.GetString("InstallingCookiecutterDeleteEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to install cookiecutter -----.
        /// </summary>
        public static string InstallingCookiecutterFailed {
            get {
                return ResourceManager.GetString("InstallingCookiecutterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing packages into virtual environment at &apos;{0}&apos;.
        /// </summary>
        public static string InstallingCookiecutterInstallPackages {
            get {
                return ResourceManager.GetString("InstallingCookiecutterInstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing pip into virtual environment at &apos;{0}&apos;.
        /// </summary>
        public static string InstallingCookiecutterInstallPip {
            get {
                return ResourceManager.GetString("InstallingCookiecutterInstallPip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Installing cookiecutter -----.
        /// </summary>
        public static string InstallingCookiecutterStarted {
            get {
                return ResourceManager.GetString("InstallingCookiecutterStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully installed cookiecutter -----.
        /// </summary>
        public static string InstallingCookiecutterSuccess {
            get {
                return ResourceManager.GetString("InstallingCookiecutterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Python 3.
        /// </summary>
        public static string InstallPythonInfoBarLink {
            get {
                return ResourceManager.GetString("InstallPythonInfoBarLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid output folder in the &apos;Create To&apos; field..
        /// </summary>
        public static string InvalidOutputFolder {
            get {
                return ResourceManager.GetString("InvalidOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to load template &apos;{0}&apos; -----.
        /// </summary>
        public static string LoadingTemplateFailed {
            get {
                return ResourceManager.GetString("LoadingTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Loading template &apos;{0}&apos; -----.
        /// </summary>
        public static string LoadingTemplateStarted {
            get {
                return ResourceManager.GetString("LoadingTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully loaded template &apos;{0}&apos; -----.
        /// </summary>
        public static string LoadingTemplateSuccess {
            get {
                return ResourceManager.GetString("LoadingTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: The template item &apos;{0}&apos; has an unsupported value_source &apos;{1}&apos;..
        /// </summary>
        public static string LoadTemplateValueSourceNotSupportedWarning {
            get {
                return ResourceManager.GetString("LoadTemplateValueSourceNotSupportedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for redirected environment at &apos;{0}&apos;.
        /// </summary>
        public static string LookingForRedirectedEnv {
            get {
                return ResourceManager.GetString("LookingForRedirectedEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to look for redirected environment at &apos;{0}&apos;.
        /// </summary>
        public static string LookingForRedirectedEnvFailed {
            get {
                return ResourceManager.GetString("LookingForRedirectedEnvFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found redirected environment at &apos;{0}&apos;.
        /// </summary>
        public static string LookingForRedirectedEnvFound {
            get {
                return ResourceManager.GetString("LookingForRedirectedEnvFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some external dependencies are missing. Click the links to install them..
        /// </summary>
        public static string MissingDependenciesInfoBarMessage {
            get {
                return ResourceManager.GetString("MissingDependenciesInfoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help me install Python.
        /// </summary>
        public static string MissingDependenciesPage_InstallPython {
            get {
                return ResourceManager.GetString("MissingDependenciesPage_InstallPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install Python 3.5 or later and restart Visual Studio to use this feature..
        /// </summary>
        public static string MissingDependenciesPage_Message {
            get {
                return ResourceManager.GetString("MissingDependenciesPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the generated folder in Solution Explorer?.
        /// </summary>
        public static string OpenInSolutionExplorerQuestion {
            get {
                return ResourceManager.GetString("OpenInSolutionExplorerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files will be added to your project..
        /// </summary>
        public static string OptionsPage_AddingToProject {
            get {
                return ResourceManager.GetString("OptionsPage_AddingToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter was invoked using the Add From Cookiecutter command. To restart and create a new project, click Home or Cancel..
        /// </summary>
        public static string OptionsPage_AddingToProjectTooltip {
            get {
                return ResourceManager.GetString("OptionsPage_AddingToProjectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Project.
        /// </summary>
        public static string OptionsPage_AddToProject {
            get {
                return ResourceManager.GetString("OptionsPage_AddToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Solution.
        /// </summary>
        public static string OptionsPage_AddToSolution {
            get {
                return ResourceManager.GetString("OptionsPage_AddToSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OptionsPage_Cancel {
            get {
                return ResourceManager.GetString("OptionsPage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string OptionsPage_Create {
            get {
                return ResourceManager.GetString("OptionsPage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and Open Folder.
        /// </summary>
        public static string OptionsPage_CreateAndOpenFolder {
            get {
                return ResourceManager.GetString("OptionsPage_CreateAndOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and Open Project.
        /// </summary>
        public static string OptionsPage_CreateAndOpenProject {
            get {
                return ResourceManager.GetString("OptionsPage_CreateAndOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create To.
        /// </summary>
        public static string OptionsPage_CreateTo {
            get {
                return ResourceManager.GetString("OptionsPage_CreateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder path for created files.
        /// </summary>
        public static string OptionsPage_CreateToAutomationName {
            get {
                return ResourceManager.GetString("OptionsPage_CreateToAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for output folder path.
        /// </summary>
        public static string OptionsPage_CreateToBrowseAutomationName {
            get {
                return ResourceManager.GetString("OptionsPage_CreateToBrowseAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder location where the files will be created. Files may be replaced if the folder is not empty, but a backup of the existing files will be created as needed..
        /// </summary>
        public static string OptionsPage_CreateToTooltip {
            get {
                return ResourceManager.GetString("OptionsPage_CreateToTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. C:\Projects\Project1.
        /// </summary>
        public static string OptionsPage_CreateToWatermark {
            get {
                return ResourceManager.GetString("OptionsPage_CreateToWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating files....
        /// </summary>
        public static string OptionsPage_CreatingFiles {
            get {
                return ResourceManager.GetString("OptionsPage_CreatingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating files. See the Output Window for details..
        /// </summary>
        public static string OptionsPage_CreatingFilesError {
            get {
                return ResourceManager.GetString("OptionsPage_CreatingFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OptionsPage_Name {
            get {
                return ResourceManager.GetString("OptionsPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for database connection.
        /// </summary>
        public static string OptionsPage_OdbcConnectionBrowseAutomationName {
            get {
                return ResourceManager.GetString("OptionsPage_OdbcConnectionBrowseAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsPage_Options {
            get {
                return ResourceManager.GetString("OptionsPage_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run additional tasks on completion.
        /// </summary>
        public static string OptionsPage_RunAdditionalTasks {
            get {
                return ResourceManager.GetString("OptionsPage_RunAdditionalTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template cloned successfully..
        /// </summary>
        public static string OptionsPage_TemplateCloneSuccessfully {
            get {
                return ResourceManager.GetString("OptionsPage_TemplateCloneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned an exit code of {1}..
        /// </summary>
        public static string ProcessExitCodeMessage {
            get {
                return ResourceManager.GetString("ProcessExitCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project with unique name &apos;{0}&apos; was not found in the current solution..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - &apos;{0}&apos; was saved as &apos;{1}&apos;..
        /// </summary>
        public static string ReplacedFile {
            get {
                return ResourceManager.GetString("ReplacedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files were backed up and then replaced:.
        /// </summary>
        public static string ReplacedFilesHeader {
            get {
                return ResourceManager.GetString("ReplacedFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to create files using template &apos;{0}&apos; -----.
        /// </summary>
        public static string RunningTemplateFailed {
            get {
                return ResourceManager.GetString("RunningTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Creating files using template &apos;{0}&apos; -----.
        /// </summary>
        public static string RunningTemplateStarted {
            get {
                return ResourceManager.GetString("RunningTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully created files using template &apos;{0}&apos; into &apos;{1}&apos; -----.
        /// </summary>
        public static string RunningTemplateSuccess {
            get {
                return ResourceManager.GetString("RunningTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}..
        /// </summary>
        public static string SearchPage_CategoryHelpTextNoUpdate {
            get {
                return ResourceManager.GetString("SearchPage_CategoryHelpTextNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}. Update is available.
        /// </summary>
        public static string SearchPage_CategoryHelpTextUpdate {
            get {
                return ResourceManager.GetString("SearchPage_CategoryHelpTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string SearchPage_CheckingUpdates {
            get {
                return ResourceManager.GetString("SearchPage_CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates completed..
        /// </summary>
        public static string SearchPage_CheckingUpdatesCompleted {
            get {
                return ResourceManager.GetString("SearchPage_CheckingUpdatesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning repository....
        /// </summary>
        public static string SearchPage_CloningRepository {
            get {
                return ResourceManager.GetString("SearchPage_CloningRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the creator.
        /// </summary>
        public static string SearchPage_Creator {
            get {
                return ResourceManager.GetString("SearchPage_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating templates. This may take a few seconds..
        /// </summary>
        public static string SearchPage_EnumeratingTemplatesTooltip {
            get {
                return ResourceManager.GetString("SearchPage_EnumeratingTemplatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates. See the Output Window for details..
        /// </summary>
        public static string SearchPage_ErrorCheckingUpdates {
            get {
                return ResourceManager.GetString("SearchPage_ErrorCheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cloning repository. See the Output Window for details..
        /// </summary>
        public static string SearchPage_ErrorCloningRepository {
            get {
                return ResourceManager.GetString("SearchPage_ErrorCloningRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing Cookiecutter. See the Output Window for details..
        /// </summary>
        public static string SearchPage_ErrorInstallingCookiecutter {
            get {
                return ResourceManager.GetString("SearchPage_ErrorInstallingCookiecutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading template. See the Output Window for details..
        /// </summary>
        public static string SearchPage_ErrorLoadingTemplate {
            get {
                return ResourceManager.GetString("SearchPage_ErrorLoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string SearchPage_LinksGitHub {
            get {
                return ResourceManager.GetString("SearchPage_LinksGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string SearchPage_LinksGitHubIssues {
            get {
                return ResourceManager.GetString("SearchPage_LinksGitHubIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string SearchPage_LinksGitHubWiki {
            get {
                return ResourceManager.GetString("SearchPage_LinksGitHubWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string SearchPage_LoadingSearchResults {
            get {
                return ResourceManager.GetString("SearchPage_LoadingSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading template....
        /// </summary>
        public static string SearchPage_LoadingTemplate {
            get {
                return ResourceManager.GetString("SearchPage_LoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string SearchPage_LoadMore {
            get {
                return ResourceManager.GetString("SearchPage_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next.
        /// </summary>
        public static string SearchPage_NextButton {
            get {
                return ResourceManager.GetString("SearchPage_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available..
        /// </summary>
        public static string SearchPage_NoTemplateDescriptionAvailable {
            get {
                return ResourceManager.GetString("SearchPage_NoTemplateDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Solution Explorer.
        /// </summary>
        public static string SearchPage_OpenInSolutionExplorer {
            get {
                return ResourceManager.GetString("SearchPage_OpenInSolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing cookiecutter for first time use....
        /// </summary>
        public static string SearchPage_PreparingFirstTime {
            get {
                return ResourceManager.GetString("SearchPage_PreparingFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing the cookiecutter package from the Python Package Index. This may take a few minutes..
        /// </summary>
        public static string SearchPage_PreparingFirstTimeTooltip {
            get {
                return ResourceManager.GetString("SearchPage_PreparingFirstTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPage_Search {
            get {
                return ResourceManager.GetString("SearchPage_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms.
        /// </summary>
        public static string SearchPage_SearchAutomationName {
            get {
                return ResourceManager.GetString("SearchPage_SearchAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search terms or template location (git repository URL or path to local folder).
        /// </summary>
        public static string SearchPage_SearchTooltip {
            get {
                return ResourceManager.GetString("SearchPage_SearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search terms or template location.
        /// </summary>
        public static string SearchPage_SearchWatermark {
            get {
                return ResourceManager.GetString("SearchPage_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        public static string SearchPage_UpdateAvailableTooltip {
            get {
                return ResourceManager.GetString("SearchPage_UpdateAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating template....
        /// </summary>
        public static string SearchPage_UpdatingTemplate {
            get {
                return ResourceManager.GetString("SearchPage_UpdatingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template updated..
        /// </summary>
        public static string SearchPage_UpdatingTemplateCompleted {
            get {
                return ResourceManager.GetString("SearchPage_UpdatingTemplateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating template. See the Output Window for details..
        /// </summary>
        public static string SearchPage_UpdatingTemplateError {
            get {
                return ResourceManager.GetString("SearchPage_UpdatingTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit {0} on GitHub.
        /// </summary>
        public static string SearchPage_VisitOwnerOnGitHub {
            get {
                return ResourceManager.GetString("SearchPage_VisitOwnerOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        ///
        ///You can get more information by running Visual Studio with the /log parameter on the command line, and then examining the file &apos;{0}&apos;, or by checking the Event Log..
        /// </summary>
        public static string SeeActivityLog {
            get {
                return ResourceManager.GetString("SeeActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check online for updates to installed templates..
        /// </summary>
        public static string Settings_CheckForTemplateUpdate_Description {
            get {
                return ResourceManager.GetString("Settings_CheckForTemplateUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updated templates.
        /// </summary>
        public static string Settings_CheckForTemplateUpdate_Name {
            get {
                return ResourceManager.GetString("Settings_CheckForTemplateUpdate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the feed file. Feed files have one template URL on each line..
        /// </summary>
        public static string Settings_FeedUrl_Description {
            get {
                return ResourceManager.GetString("Settings_FeedUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended feed URL.
        /// </summary>
        public static string Settings_FeedUrl_Name {
            get {
                return ResourceManager.GetString("Settings_FeedUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_Category {
            get {
                return ResourceManager.GetString("Settings_General_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the help information bar..
        /// </summary>
        public static string Settings_ShowHelp_Description {
            get {
                return ResourceManager.GetString("Settings_ShowHelp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Help.
        /// </summary>
        public static string Settings_ShowHelp_Name {
            get {
                return ResourceManager.GetString("Settings_ShowHelp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string TemplateCategoryCustom {
            get {
                return ResourceManager.GetString("TemplateCategoryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string TemplateCategoryGitHub {
            get {
                return ResourceManager.GetString("TemplateCategoryGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string TemplateCategoryInstalled {
            get {
                return ResourceManager.GetString("TemplateCategoryInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string TemplateCategoryRecommended {
            get {
                return ResourceManager.GetString("TemplateCategoryRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter.
        /// </summary>
        public static string ToolWindowCaption {
            get {
                return ResourceManager.GetString("ToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio was unable to launch the elevated process..
        /// </summary>
        public static string UnableToElevate {
            get {
                return ResourceManager.GetString("UnableToElevate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in {3} ({1}:{2})
        ///{0}.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to update template &apos;{0}&apos; -----.
        /// </summary>
        public static string UpdatingTemplateFailed {
            get {
                return ResourceManager.GetString("UpdatingTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Updating template &apos;{0}&apos; -----.
        /// </summary>
        public static string UpdatingTemplateStarted {
            get {
                return ResourceManager.GetString("UpdatingTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully updated template &apos;{0}&apos; -----.
        /// </summary>
        public static string UpdatingTemplateSuccess {
            get {
                return ResourceManager.GetString("UpdatingTemplateSuccess", resourceCulture);
            }
        }
    }
}
