//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CookiecutterTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CookiecutterTools.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files were successfully created, but there was an issue adding the files to your project.\n{0}.
        /// </summary>
        internal static string AddToProjectError {
            get {
                return ResourceManager.GetString("AddToProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Check for template updates canceled -----.
        /// </summary>
        internal static string CheckingForAllUpdatesCanceled {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to check for template updates -----.
        /// </summary>
        internal static string CheckingForAllUpdatesFailed {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Checking for template updates -----.
        /// </summary>
        internal static string CheckingForAllUpdatesStarted {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully checked for template updates -----.
        /// </summary>
        internal static string CheckingForAllUpdatesSuccess {
            get {
                return ResourceManager.GetString("CheckingForAllUpdatesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for an update..
        /// </summary>
        internal static string CheckingTemplateUpdateError {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        internal static string CheckingTemplateUpdateFound {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine if an update is available..
        /// </summary>
        internal static string CheckingTemplateUpdateInconclusive {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is already up-to-date..
        /// </summary>
        internal static string CheckingTemplateUpdateNotFound {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Checking for update to template &apos;{0}&apos; from &apos;{1}&apos; -----.
        /// </summary>
        internal static string CheckingTemplateUpdateStarted {
            get {
                return ResourceManager.GetString("CheckingTemplateUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A different template with the name &apos;{0}&apos; already exists in &apos;{1}&apos;.
        ///
        ///Please delete the installed template and try again..
        /// </summary>
        internal static string CloneCollisionMessage {
            get {
                return ResourceManager.GetString("CloneCollisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to clone template &apos;{0}&apos; -----.
        /// </summary>
        internal static string CloningTemplateFailed {
            get {
                return ResourceManager.GetString("CloningTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Cloning template &apos;{0}&apos; -----.
        /// </summary>
        internal static string CloningTemplateStarted {
            get {
                return ResourceManager.GetString("CloningTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully cloned template &apos;{0}&apos; to &apos;{1}&apos; -----.
        /// </summary>
        internal static string CloningTemplateSuccess {
            get {
                return ResourceManager.GetString("CloningTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string appears to be in incorrect format. Would you like to re-create it?.
        /// </summary>
        internal static string ConnectionStringFormatIncorrect {
            get {
                return ResourceManager.GetString("ConnectionStringFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; from _visual_studio section in context file should be an absolute http or https url..
        /// </summary>
        internal static string CookiecutterClient_Invalidurl {
            get {
                return ResourceManager.GetString("CookiecutterClient_Invalidurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property is required on &apos;{1}&apos;..
        /// </summary>
        internal static string CookiecutterClient_MissingProperty {
            get {
                return ResourceManager.GetString("CookiecutterClient_MissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter generated files must have a templated folder..
        /// </summary>
        internal static string CookiecutterClient_MoveToDesiredFolderTemplatedFolderNotFound {
            get {
                return ResourceManager.GetString("CookiecutterClient_MoveToDesiredFolderTemplatedFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is referenced from _visual_studio section in context file but was not found..
        /// </summary>
        internal static string CookiecutterClient_ReferenceNotFound {
            get {
                return ResourceManager.GetString("CookiecutterClient_ReferenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; from _visual_studio section in context file should be of type &apos;{1}&apos;, instead of &apos;{2}&apos;..
        /// </summary>
        internal static string CookiecutterClient_WrongJsonType {
            get {
                return ResourceManager.GetString("CookiecutterClient_WrongJsonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the template from this folder?
        ///
        ///{0}.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to delete template &apos;{0}&apos; -----.
        /// </summary>
        internal static string DeletingTemplateFailed {
            get {
                return ResourceManager.GetString("DeletingTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Deleting template &apos;{0}&apos; -----.
        /// </summary>
        internal static string DeletingTemplateStarted {
            get {
                return ResourceManager.GetString("DeletingTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully deleted template &apos;{0}&apos; -----.
        /// </summary>
        internal static string DeletingTemplateSuccess {
            get {
                return ResourceManager.GetString("DeletingTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve results from feed.
        /// </summary>
        internal static string FeedLoadError {
            get {
                return ResourceManager.GetString("FeedLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve results from GitHub.
        /// </summary>
        internal static string GitHubSearchError {
            get {
                return ResourceManager.GetString("GitHubSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter makes it easy to generate code from a template..
        /// </summary>
        internal static string InfoBarMessage {
            get {
                return ResourceManager.GetString("InfoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more..
        /// </summary>
        internal static string InfoBarMessageLink {
            get {
                return ResourceManager.GetString("InfoBarMessageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Git.
        /// </summary>
        internal static string InstallGitInfoBarLink {
            get {
                return ResourceManager.GetString("InstallGitInfoBarLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to install cookiecutter -----.
        /// </summary>
        internal static string InstallingCookiecutterFailed {
            get {
                return ResourceManager.GetString("InstallingCookiecutterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Installing cookiecutter -----.
        /// </summary>
        internal static string InstallingCookiecutterStarted {
            get {
                return ResourceManager.GetString("InstallingCookiecutterStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully installed cookiecutter -----.
        /// </summary>
        internal static string InstallingCookiecutterSuccess {
            get {
                return ResourceManager.GetString("InstallingCookiecutterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Python 3.
        /// </summary>
        internal static string InstallPythonInfoBarLink {
            get {
                return ResourceManager.GetString("InstallPythonInfoBarLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid output folder in the &apos;Create To&apos; field..
        /// </summary>
        internal static string InvalidOutputFolder {
            get {
                return ResourceManager.GetString("InvalidOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to load template &apos;{0}&apos; -----.
        /// </summary>
        internal static string LoadingTemplateFailed {
            get {
                return ResourceManager.GetString("LoadingTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Loading template &apos;{0}&apos; -----.
        /// </summary>
        internal static string LoadingTemplateStarted {
            get {
                return ResourceManager.GetString("LoadingTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully loaded template &apos;{0}&apos; -----.
        /// </summary>
        internal static string LoadingTemplateSuccess {
            get {
                return ResourceManager.GetString("LoadingTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some external dependencies are missing. Click the links to install them..
        /// </summary>
        internal static string MissingDependenciesInfoBarMessage {
            get {
                return ResourceManager.GetString("MissingDependenciesInfoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the generated folder in Solution Explorer?.
        /// </summary>
        internal static string OpenInSolutionExplorerQuestion {
            get {
                return ResourceManager.GetString("OpenInSolutionExplorerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned an exit code of {1}..
        /// </summary>
        internal static string ProcessExitCodeMessage {
            get {
                return ResourceManager.GetString("ProcessExitCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project with unique name &apos;{0}&apos; was not found in the current solution..
        /// </summary>
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - &apos;{0}&apos; was saved as &apos;{1}&apos;..
        /// </summary>
        internal static string ReplacedFile {
            get {
                return ResourceManager.GetString("ReplacedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files were replaced, and a backup of the original file was created:.
        /// </summary>
        internal static string ReplacedFilesHeader {
            get {
                return ResourceManager.GetString("ReplacedFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to create files using template &apos;{0}&apos; -----.
        /// </summary>
        internal static string RunningTemplateFailed {
            get {
                return ResourceManager.GetString("RunningTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Creating files using template &apos;{0}&apos; -----.
        /// </summary>
        internal static string RunningTemplateStarted {
            get {
                return ResourceManager.GetString("RunningTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully created files using template &apos;{0}&apos; into &apos;{1}&apos; -----.
        /// </summary>
        internal static string RunningTemplateSuccess {
            get {
                return ResourceManager.GetString("RunningTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        ///
        ///You can get more information by running Visual Studio with the /log parameter on the command line, and then examining the file &apos;{0}&apos;, or by checking the Event Log..
        /// </summary>
        internal static string SeeActivityLog {
            get {
                return ResourceManager.GetString("SeeActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string TemplateCategoryCustom {
            get {
                return ResourceManager.GetString("TemplateCategoryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string TemplateCategoryGitHub {
            get {
                return ResourceManager.GetString("TemplateCategoryGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string TemplateCategoryInstalled {
            get {
                return ResourceManager.GetString("TemplateCategoryInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string TemplateCategoryRecommended {
            get {
                return ResourceManager.GetString("TemplateCategoryRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookiecutter.
        /// </summary>
        internal static string ToolWindowCaption {
            get {
                return ResourceManager.GetString("ToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in {3} ({1}:{2})
        ///{0}.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Failed to update template &apos;{0}&apos; -----.
        /// </summary>
        internal static string UpdatingTemplateFailed {
            get {
                return ResourceManager.GetString("UpdatingTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Updating template &apos;{0}&apos; -----.
        /// </summary>
        internal static string UpdatingTemplateStarted {
            get {
                return ResourceManager.GetString("UpdatingTemplateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Successfully updated template &apos;{0}&apos; -----.
        /// </summary>
        internal static string UpdatingTemplateSuccess {
            get {
                return ResourceManager.GetString("UpdatingTemplateSuccess", resourceCulture);
            }
        }
    }
}
